## Root is the relative path from this yaml file to the root of the git repo.
## Project name is an optional name that is inserted into saved output files. This is useful if you want to have multiple dvc yamls in the same repo.
root: '..'
project_name: '.'

## Pipeline parameters determine which methods are used in each stage.
pipeline:
    processor_list: ['Regressionalize', 'Lag', 'Diff', 'Custom_Transform']
    model_list: ['LinearRegressor', 'PytorchNeuralNetworkRegressor']
    metric_list: ['Scatter', 'Weighted_R']

parameters:
    processors:
        global:
            train_partition_ids: [3]
            test_partition_ids: [8]
            label_column: 'responder_6'
            fold_column: 'date_id'
            num_folds: 5
        Regressionalize: {}
        Lag: {}
        Diff: {}
        Custom_Transform: {}
    models:
        LinearRegressor: {}
        PytorchNeuralNetworkRegressor: 
            dimension: 16
            learning_rate: 0.03
            dropout_rate: 0.1
            loss_function_name: 'MSELoss'
            optimizer_name: 'SGD'
            max_epochs: 1000
            seed: 363
            callback_period: 5
    metrics:
        Scatter:
            figsize: 8
            alpha: 0.1
            point_size: 5
        Weighted_R: {}
