## Root is the relative path from this yaml file to the root of the git repo.
## Project name is an optional name that is inserted into saved output files. This is useful if you want to have multiple dvc yamls in the same repo.
root: '..'
project_name: '.'

## Pipeline parameters determine which methods are used in each stage.
pipeline:
    processor_list: ['Regressionalize']
    # model_list: ['LinearRegressor', 'PytorchNeuralNetwork', 'PytorchNeuralNetworkRestricted']
    model_list: ['LinearRegressor']
    # metric_list: ['MSEloss', 'PearsonScatter', 'SpearmanScatter']
    metric_list: ['Scatter']

parameters:
    processors:
        global:
            fold_column: 'date_id'
            num_folds: 5
            partition_ids: [0]
            label_column: 'responder_6'
        Regressionalize: {}
    models:
        LinearRegressor: {}
        PytorchNeuralNetwork: {}
        PytorchNeuralNetworkRestricted: {}
    metrics:
        MSEloss: {}
        Scatter: {}        