## Root is the relative path from this yaml file to the root of the git repo.
## Project name is an optional name that is inserted into saved output files. This is useful if you want to have multiple dvc yamls in the same repo.
root: '..'
project_name: '.'

## Pipeline parameters determine which methods are used in each stage.
pipeline:
    processor_list: ['Regressionalize']
    model_list: ['LinearRegression', 'PytorchNeuralNetwork', 'PytorchNeuralNetworkRestricted']
    metric_list: ['MSEloss', 'PearsonScatter', 'SpearmanScatter']

parameters:
    processors:
        global:
        Regressionalize: {}
    models:
        LinearRegression: {}
        PytorchNeuralNetwork: {}
        PytorchNeuralNetworkRestricted: {}
    metrics:
        MSEloss: {}
        PearsonScatter: {}
        SpearmanScatter: {}
        